name: CI workflow
on: 
  push: 
    # Currently runs on all branches
  pull_request:
     # Currently runs on all branches
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # check out code in repo onto the runner
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Latest Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib pytest
    - name: mini test
      run: |
        python -c "import numpy; import scipy; import matplotlib; print('All imports successful')"

# To do:
# Build python environment
# Lint
# Coverage testing
# Run existing unit tests
# When packaging has been set up: 
# - add our package to dependencies to automatically install? if that is something we need to do?
# - pip install -r requirements.txt

