name: CI workflow
on: 
  push: 
    # Currently runs on all branches
  pull_request:
    # Currently runs on all branches
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # check out code in repo onto the runner
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Latest Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install .
        # ^ Should look for setup.py file
    - name: Lint with flake8
      run: |
        flake8 . --exit-zero --max-complexity=10 --max-line-length=127
        # Output error in CI workflow log, but do not fail the workflow if there are linting errors
        # max-complexity=10 specifies the max number of paths through a function before a linting error is returned
        # max-line-length=127 sets the maximum allowed line length before a linting error is returned
    - name: Run unit tests with coverage reporting
      run: |
        pytest --cov=./pkmodel --cov-report=xml
        cat coverage.xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: coverage.xml

